name: tekartik_firebase_functions_sim
description: Firebase functions sim
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  meta:
  tekartik_app_web_socket:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_web_socket
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart3a
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase_local
  tekartik_firebase_sim:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase_sim
dev_dependencies:
  lints: ">=5.0.0"
  tekartik_firebase_functions_test:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      ref: dart3a
      path: firebase_functions_test
  test: ">=1.24.0"
resolution: workspace
