# Dependabot configuration file.
# See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2

enable-beta-ecosystems: true

updates:
  - package-ecosystem: "pub"
    directory: "."
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "firebase_functions"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "firebase_functions_http"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "firebase_functions_io"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "firebase_functions_test"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "functions_call"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "functions_call_http"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "functions_call_sim"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pub"
    directory: "repo_support"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
