name: tekartik_firebase_functions_node
description: Firebase functions node
version: 0.0.2
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.63 <3.0.0'

dependencies:
  js: any
  tekartik_firebase_functions:
    git:
      url: git://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart2
  sembast: '>=1.9.0-dev.1'
  uuid: '>=1.0.0'
  firebase_functions_interop: ">=1.0.0-dev.4"
  firebase_admin_interop: ">=1.0.0-dev.10"

dev_dependencies:
  test: "^1.2.0"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
  build_runner: ">=0.9.0"
  build_node_compilers: ">=0.1.8"


dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions