name: tekartik_firebase_functions_node
description: Firebase functions node
version: 0.3.3
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  js: any
  tekartik_firebase_functions:
    git:
      url: git://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart2
    version: '>=0.3.3'
  tekartik_firebase_functions_io:
    git:
      url: git://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_io
      ref: dart2
    version: '>=0.3.3'
  tekartik_firebase_firestore_node:
    git:
      url: git://github.com/tekartik/firebase_firestore.dart
      path: firestore_node
      ref: dart2
    version: '>=0.8.0'

  sembast: '>=1.9.0-dev.1'
  uuid: '>=1.0.0'
  # firebase_functions_interop: ">=1.0.0 <1.0.2"
  firebase_functions_interop: ">=1.0.1 <3.0.0"
  # node_io: ">=1.0.0-dev.10.0 <1.0.0"
  node_io: '>=1.0.1+2 <3.0.0'
  firebase_admin_interop: ">=1.1.0"

dev_dependencies:
  test: "^1.2.0"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
  tekartik_firebase_functions_test:
    git:
      url: git://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_test
      ref: dart2
    version: '>=0.2.1'
  tekartik_http_node:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_node
      ref: dart2
    version: '>=0.4.0+1'
  tekartik_http_io:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_io
      ref: dart2
    version: '>=0.1.0'
  build_runner: ">=0.9.0"
  build_node_compilers: ">=0.1.8"
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions
  tekartik_firebase_functions_io:
    path: ../firebase_functions_io
  tekartik_firebase_functions_test:
    path: ../firebase_functions_test