language: dart
sudo: required
dist: trusty
dart:
  - stable
  - beta
  - dev

addons:
  chrome: stable

before_script:
  - pushd repo_support
  - pub get
script:
  - dart tool/travis.dart
matrix:
  allow_failures:
    - dart: dev

cache:
  directories:
    - $HOME/.pub-cache