# Created with https://github.com/dart-lang/mono_repo
language: dart

sudo: required
addons:
  chrome: stable

before_install:
  - nvm install node
  - node --version

jobs:
  include:
    - stage: test
      script: dart ./tool/travis.dart
      dart: dev
    - stage: test
      script: dart ./tool/travis.dart
      dart: stable

stages:
  - test

# Only building master means that we don't run two builds for each pull request.
# branches:
#  only: [master]

cache:
  directories:
    - $HOME/.pub-cache