name: tekartik_firebase_repo
description: Firebase repo (tools)
version: 0.2.0+4
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
  grinder: any
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.3.4'
