name: _
publish_to: none
environment:
  sdk: ^3.9.0
workspace:
  - firebase_functions
  - firebase_functions_http
  - firebase_functions_io
  - firebase_functions_sim
  - firebase_functions_test
  - functions_call
  - functions_call_http
  - repo_support
  - functions_call_sim
