name: tekartik_firebase_functions_call_http
description: Firebase functions call http
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      ref: dart3a
      path: firebase
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      ref: dart3a
      path: firebase_functions
  tekartik_firebase_functions_call:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      ref: dart3a
      path: functions_call

dev_dependencies:
  tekartik_firebase_functions_http:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      ref: dart3a
      path: firebase_functions_http
  lints: '>=4.0.0'
  test: '>=1.24.0'

dependency_overrides:
  tekartik_firebase_functions_call:
    path: ../functions_call
  tekartik_firebase_functions:
    path: ../firebase_functions
  tekartik_firebase_functions_http:
    path: ../firebase_functions_http