name: tekartik_firebase_functions
description: Firebase functions
version: 0.0.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <2.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http

dev_dependencies:
  test: ">=0.12.37"
  dev_test: any
