name: tekartik_firebase_functions
description: Firebase functions
version: 0.2.0+1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: dart2

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
