name: tekartik_firebase_functions
description: Firebase functions
version: 0.2.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: git://github.com/tekartik/http.dart
      path: http
      ref: dart2
    version: '>=0.4.0+1'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  process_run: '>=0.10.0+1'
