name: tekartik_firebase_functions
description: Firebase functions
version: 0.3.13
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      path: http
      ref: dart2_3
    version: '>=0.4.0+1'
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart2_3
    version: '>=0.8.0'
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      path: auth
      ref: dart2_3
    version: '>=0.9.0'
dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  process_run: '>=0.10.0+1'