name: tekartik_firebase_functions_test
description: Firebase functions_test
version: 0.2.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  test:
  meta:
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart2_3
    version: '>=0.2.1'

dev_dependencies:
  dev_test: any
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions