name: tekartik_firebase_functions_test
description: Firebase functions_test
version: 0.2.1
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  meta:
  tekartik_firebase_functions:
    git:
      url: git://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart2
    version: '>=0.2.1'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions
  tekartik_firebase_functions_http:
    path: ../firebase_functions_http