name: tekartik_firebase_functions_test
description: Firebase functions_test
version: 0.2.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.5.0

dependencies:
  meta:
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart3a
    version: '>=0.2.1'

dev_dependencies:
  test:
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions
