name: tekartik_firebase_functions_test
description: Firebase functions_test
version: 0.2.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.6.0

dependencies:
  meta: ">=1.15.0"
  http:
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart3a
    version: '>=0.2.1'
  tekartik_firebase_functions_call:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      ref: dart3a
      path: functions_call
  tekartik_http:
    git:
      url: https://github.com/tekartik/http.dart
      ref: dart3a
      path: http

dev_dependencies:
  test: ">=1.24.0"
  process_run: ">=1.2.1+1"

resolution: workspace
