name: tekartik_firebase_functions_call
description: Firebase functions call
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions

dev_dependencies:
  lints: ">=5.0.0"
  test: '>=1.24.0'

resolution: workspace
