name: tekartik_firebase_functions_call_sim
description: Firebase functions call sim
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  tekartik_firebase_functions_call:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      ref: dart3a
      path: functions_call
  tekartik_firebase_functions_sim:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_sim
      ref: dart3a

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
