name: tekartik_firebase_functions_io
description: Firebase functions io simulation
version: 0.1.0
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.0.0-dev.54 <3.0.0'

dependencies:
  uuid: '>=1.0.0'
  tekartik_firebase_functions:
    git:
      url: git://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart2
    version: '>=0.1.0'
  tekartik_firebase_sim_io:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sim_io
      ref: dart2
  shelf: any

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  build_runner: ">=0.8.8"
  build_test:
  tekartik_http_io:
    git:
      url: git://github.com/tekartik/http.dart
      path: http_io
      ref: dart2

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions
