name: tekartik_firebase_functions_http
description: Firebase functions http simulation
version: 0.4.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: ^3.5.0

dependencies:
  path:
  uuid: '>=1.0.0'
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart3a
    version: '>=0.4.1'
  shelf: any
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart3a
    version: '>=0.5.8'
  http:
  tekartik_firebase_firestore:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore
      ref: dart3a
    version: '>=1.1.4'
  tekartik_firebase:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase
      ref: dart3a
    version: '>=0.4.0'
  tekartik_firebase_local:
    git:
      url: https://github.com/tekartik/firebase.dart
      path: firebase_local
      ref: dart3a
  tekartik_firebase_auth:
    git:
      url: https://github.com/tekartik/firebase_auth.dart
      ref: dart3a
      path: auth
dev_dependencies:
  test: ">=1.2.0"
  build_runner: ">=0.8.8"
  build_test:
  tekartik_firebase_firestore_sembast:
    git:
      url: https://github.com/tekartik/firebase_firestore.dart
      path: firestore_sembast
      ref: dart3a
    version: '>=0.8.0'
  tekartik_firebase_functions_test:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_test
      ref: dart3a
    version: '>=0.2.1'
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions
  tekartik_firebase_functions_test:
    path: ../firebase_functions_test
