name: tekartik_firebase_functions_http
description: Firebase functions http simulation
version: 0.4.1
publish_to: none
#homepage: https://www.example.com
#author: alex <email@example.com>

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  path:
  uuid: '>=1.0.0'
  tekartik_firebase_functions:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions
      ref: dart2_3
    version: '>=0.4.1'
  shelf: any
  tekartik_http_io:
    git:
      url: https://github.com/tekartik/http.dart
      path: http_io
      ref: dart2_3
    version: '>=0.5.8'

dev_dependencies:
  test: ">=1.2.0"
  dev_test: any
  build_runner: ">=0.8.8"
  build_test:

  tekartik_firebase_functions_test:
    git:
      url: https://github.com/tekartik/firebase_functions.dart
      path: firebase_functions_test
      ref: dart2_3
    version: '>=0.2.1'
  process_run: '>=0.10.0+1'

dependency_overrides:
  tekartik_firebase_functions:
    path: ../firebase_functions
  tekartik_firebase_functions_test:
    path: ../firebase_functions_test