name: app_common_repo_support
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

dev_dependencies:
  dev_build: ">=1.1.2"
  test: ">=1.24.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
    version: '>=0.1.0'
dependency_overrides:
resolution: workspace
#  tekartik_build_utils:
#    path: ../../../tekartik/build_utils.dart
